apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmi
  labels:
    app: hmi
spec:
  replicas: {{ .Values.hmi.replicas }}
  selector:
    matchLabels:
      app: hmi
  template:
    metadata:
      labels:
        app: hmi
    spec:
      containers:
        - name: hmi
          image: {{ .Values.hmi.image }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{- toYaml .Values.hmi.resources | nindent 12 }}