apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-server-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-sa