# -*- coding: utf-8 -*-
"""Inference_Birds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOszzPc19vuHCzrqwFrG5bteqImxYzgG
"""

import os
import numpy as np
import tensorflow as tf
from PIL import Image
import csv
from google.colab import drive

drive.mount('/content/drive')

# ---------------- CONFIG ----------------
MODEL_PATH = "/content/drive/MyDrive/Birds_Dataset3_model/bird_classifier_float_v1.tflite"
CSV_PATH = "/content/drive/MyDrive/Birds_Dataset3_model/class_names.csv"
TEST_DIR = "/content/drive/MyDrive/Birds_Dataset3_model/Testing"
IMG_SIZE = 300

# ---------------- LOAD MODEL ----------------
interpreter = tf.lite.Interpreter(model_path=MODEL_PATH)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_dtype = input_details[0]["dtype"]
print("Model input:", input_dtype)

# ---------------- LOAD CLASSES ----------------
class_names = []
with open(CSV_PATH, "r") as f:
    for row in csv.reader(f):
        if row:
            class_names.append(row[0])

# ---------------- PREPROCESS ----------------
def preprocess(path):
    img = Image.open(path).convert("RGB")
    img = img.resize((IMG_SIZE, IMG_SIZE))
    img = np.array(img, dtype=np.float32)  # 0–255
    return np.expand_dims(img, axis=0)


# ---------------- INFERENCE ----------------
for file in sorted(os.listdir(TEST_DIR)):
    if not file.lower().endswith(("jpg", "png", "jpeg")):
        continue

    path = os.path.join(TEST_DIR, file)
    input_data = preprocess(path)

    interpreter.set_tensor(input_details[0]["index"], input_data)
    interpreter.invoke()

    output = interpreter.get_tensor(output_details[0]["index"])[0]
    idx = np.argmax(output)
    conf = output[idx]

    print(f"{file} → {class_names[idx]} ({conf*100:.1f}%)")