apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: echo-storage-class-gke
  resources:
    requests:
      storage: 10Gi
