apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out ./k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: echo-store
  name: echo-store
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: echo-store
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out ./k8s
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/echo-net-echo-net: "true"
        io.kompose.service: echo-store
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: EchoNet
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root_password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: ts-mongodb
          name: ts-mongodb-cont
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
status: {}
