"""
response_schema.py

This file defines the proposed standard inference response
"""

from dataclasses import dataclass, asdict
from typing import Optional, Dict, Any


@dataclass
class InferenceResponse:
    """
    Standard inference response generated by the prototype Engine.
    """

    status: str
    timestamp: str

    species: Optional[str]
    confidence: Optional[float]

    sensorId: str

    microphoneLLA: Optional[Dict[str, float]]
    animalEstLLA: Optional[Dict[str, float]]
    animalTrueLLA: Optional[Dict[str, float]]

    animalLLAUncertainty: Optional[float]

    audioClip: Optional[str]

    sampleRate: int

    error: Optional[Dict[str, Any]]

    def to_dict(self) -> dict:
        """
        Convert the response into a Python dictionary.
        """
        return asdict(self)