apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: "enpoint1"
      port: 9000
      targetPort: 9000
    - name: "enpoint2"
      port: 9080
      targetPort: 9080
  type: ClusterIP
