global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "project-echo-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "echo_api:9000"

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080"
