import logging
import os

from fastapi import FastAPI, Body, HTTPException, status, APIRouter, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from app.errors import (
    StandardizeErrorResponseMiddleware,
    detection_exception_handler,
    http_exception_handler,
    unhandled_exception_handler,
    validation_exception_handler,
)
from app.exceptions import DetectionError
from app.middleware.correlation_id import add_correlation_id
from app.routers import species_predictor
from app.routers import auth_router
from app.routers import admin_budget, admin_services
from fastapi.responses import Response, JSONResponse
from fastapi.encoders import jsonable_encoder
from pydantic import BaseModel, Field, EmailStr
from bson import ObjectId
from typing import Optional, List
from app.routers import insights
import datetime
import pymongo
import json 
from pymongo.errors import ConnectionFailure, ExecutionTimeout

from app.routers import hmi, engine, sim, two_factor
from app.routers import public
from app.logging_config import configure_logging
from app.config import settings
from app.metrics import PrometheusMiddleware, metrics_router

configure_logging() #
logger = logging.getLogger(__name__)

# ✅ Add metadata here
app = FastAPI(
    title="Project Echo API",
    description="""
    Project Echo is an IoT-based system designed to record and analyze audio data for species identification and ecosystem monitoring.

    This API provides endpoints to:
    - Upload audio files
    - Simulate audio responses
    - Interface with HMI and audio engine modules
    """,
    version="1.0.0"
)

# Log API startup in structured JSON format
@app.on_event("startup")
async def log_api_startup():
    logger.info(f"API Server listening on port {settings.api_port}")

# Routers
from .routers import add_csv_output_option, audio_upload_router
from app.routers import species_predictor, auth_router, detections, hmi, engine, sim, two_factor, public, iot, live, sensors, payments #Websocket

from app.routers import projects
app.include_router(projects.router)

app.add_exception_handler(HTTPException, http_exception_handler)
app.add_exception_handler(RequestValidationError, validation_exception_handler)
app.add_exception_handler(DetectionError, detection_exception_handler)
app.add_exception_handler(Exception, unhandled_exception_handler)
app.add_middleware(StandardizeErrorResponseMiddleware)

# ✅ CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.add_middleware(PrometheusMiddleware)
logger = logging.getLogger(__name__)


async def database_unavailable_handler(request: Request, exc: Exception):
    logger.warning(
        "Database unavailable for %s %s (%s)",
        request.method,
        request.url.path,
        exc.__class__.__name__,
    )
    return JSONResponse(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        content={
            "error": "Database Unavailable",
            "message": "The database is temporarily unavailable. Please try again later.",
        },
    )


app.add_exception_handler(ConnectionFailure, database_unavailable_handler)
app.add_exception_handler(ExecutionTimeout, database_unavailable_handler)


######### MQTT live event handling (FR-A2)
from app.services.mqtt_client import start_mqtt_client, get_connection_state, get_latest_events

@app.on_event("startup")
def startup_mqtt():
    start_mqtt_client()

@app.get("/mqtt/connection-state", tags=["mqtt"])
def mqtt_connection_state():
    return {"state": get_connection_state()}

@app.get("/mqtt/latest-events", tags=["mqtt"])
def mqtt_latest_events():
    from app.routers.hmi import show_latest_events

    events = [
        {"eventType": "vocalization", **event}
        for event in show_latest_events(limit=20)
    ]
    events += [
        event for event in get_latest_events()
        if event.get("eventType") != "vocalization"
    ]

    return {"events": events}


# Correlate every response and application log entry (C9.2). This middleware
# is registered last so it is the outermost user middleware and can observe
# responses generated by the other middleware.
add_correlation_id(app)

app.include_router(audio_upload_router.router, tags=['audio'], prefix='/api')


# ✅ Include routers
app.include_router(hmi.router, tags=['hmi'], prefix='/hmi')
app.include_router(engine.router, tags=['engine'], prefix='/engine')
app.include_router(sim.router, tags=['sim'], prefix='/sim')
app.include_router(two_factor.router)
app.include_router(admin_budget.router, tags=["admin"], prefix="/api")
app.include_router(admin_services.router, tags=["admin"], prefix="/api")

app.include_router(public.router, tags=['public'], prefix='/public')

'''try:
    file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'echo_config.json')
    with open(file_path, 'r') as f:
        echo_config = json.load(f)
    print(f"Echo API echo_config successfully loaded", flush=True)
except:
    print(f"Could not API echo_config : {file_path}") 
print(f" database names: {client.list_database_names()}")
'''

app.include_router(iot.router, tags=['iot'], prefix='/iot')
app.include_router(sensors.router, tags=['sensors'], prefix='/sensors')
app.include_router(payments.router)
app.include_router(live.router, tags=["live"])
app.include_router(species_predictor.router, tags=["predict"])
app.include_router(metrics_router)



# ✅ Root endpoint
app.include_router(insights.router, tags=["insights"])

# --- Root Endpoint ---
@app.get("/", response_description="API Root")
def show_home():
    return 'Welcome to Project Echo API. Visit /docs for interactive documentation.'


@app.get("/api-info", tags=["public"], summary="Return API service information")
def api_info():
    """Provide clients with stable links to the service documentation."""
    return {
        "name": app.title,
        "version": app.version,
        "docs_url": app.docs_url,
        "openapi_url": app.openapi_url,
    }


app.include_router(auth_router.router, tags=["auth"], prefix="/api")
app.include_router(detections.router)
from app.routers import similar_detections
app.include_router(similar_detections.router)

# ✅ /openapi-export - fetch live OpenAPI spec
@app.get("/openapi-export", include_in_schema=False)
async def get_openapi_spec():
    """
    Returns the current OpenAPI spec generated by FastAPI.
    Used for downloading and converting to YAML.
    """
    return app.openapi()

# ✅ /spec/summary - for OpenAPI spec verification/debug
@app.get("/spec/summary", tags=["debug"], include_in_schema=False)
async def get_spec_summary():
    """
    Returns a summary of the OpenAPI spec for deployment verification.
    """
    spec = app.openapi()
    return {
        "title": spec.get("info", {}).get("title"),
        "version": spec.get("info", {}).get("version"),
        "number_of_paths": len(spec.get("paths", {})),
        "tags": [tag.get("name") for tag in spec.get("tags", []) if "name" in tag]
    }

# ✅ Save OpenAPI spec to file when app starts
def export_openapi_to_file():
    """
    Saves the OpenAPI spec to a file on startup.
    Creates the 'backend' folder if it doesn't exist.
    """
    output_dir = "backend"
    os.makedirs(output_dir, exist_ok=True)  # creates the folder if it doesn't exist
    output_path = os.path.join(output_dir, "project-echo-openapi.json")

    with open(output_path, "w") as f:
        json.dump(app.openapi(), f, indent=2)

    logger.info(f"OpenAPI spec exported to {output_path}")

export_openapi_to_file()
