import json
import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app import config
from app.error_handlers import register_exception_handlers
from app.middleware.correlation_id import add_correlation_id
from app.middleware.security_headers import add_security_headers
from app.routers import (
    admin_budget,
    admin_services,
    audio_upload_router,
    auth_router,
    detections,
    engine,
    hmi,
    insights,
    iot,
    projects,
    public,
    sensors,
    sim,
    species_predictor,
    two_factor,
)

# ✅ Add metadata here
app = FastAPI(
    title="Project Echo API",
    description="""
    Project Echo is an IoT-based system designed to record and analyze audio data for species identification and ecosystem monitoring.

    This API provides endpoints to:
    - Upload audio files
    - Simulate audio responses
    - Interface with HMI and audio engine modules
    """,
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=config.cors_allowed_origins(),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global exception handlers (C4.3, A3.2 and C16.1)
register_exception_handlers(app)

# Security response headers
# Adds X-Content-Type-Options, X-Frame-Options, Referrer-Policy,
# Content-Security-Policy and related headers to every response. The Python
# equivalent of Helmet. Strict-Transport-Security is opt-in via the
# SECURITY_HSTS_ENABLED environment variable, because it is correct behind
# TLS and wrong on a local HTTP development server.
add_security_headers(app, hsts_enabled=config.hsts_enabled())

# Correlate every response and application log entry (C9.2). This middleware
# is registered last so it is the outermost user middleware and can observe
# responses generated by the other middleware.
add_correlation_id(app)

app.include_router(audio_upload_router.router, tags=['audio'], prefix='/api')


# ✅ Include routers
app.include_router(hmi.router, tags=['hmi'], prefix='/hmi')
app.include_router(engine.router, tags=['engine'], prefix='/engine')
app.include_router(sim.router, tags=['sim'], prefix='/sim')
app.include_router(two_factor.router)
app.include_router(admin_budget.router, tags=["admin"], prefix="/api")
app.include_router(admin_services.router, tags=["admin"], prefix="/api")
app.include_router(projects.router)

app.include_router(public.router, tags=['public'], prefix='/public')

'''try:
    file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'echo_config.json')
    with open(file_path, 'r') as f:
        echo_config = json.load(f)
    print(f"Echo API echo_config successfully loaded", flush=True)
except:
    print(f"Could not API echo_config : {file_path}") 
print(f" database names: {client.list_database_names()}")
'''

app.include_router(iot.router, tags=['iot'], prefix='/iot')
app.include_router(sensors.router, tags=['sensors'], prefix='/sensors')
app.include_router(species_predictor.router, tags=["predict"])



# ✅ Root endpoint
app.include_router(insights.router, tags=["insights"])

# --- Root Endpoint ---
@app.get("/", response_description="API Root")
def show_home():
    return 'Welcome to Project Echo API. Visit /docs for interactive documentation.'

app.include_router(auth_router.router, tags=["auth"], prefix="/api")
app.include_router(detections.router)

# ✅ /openapi-export - fetch live OpenAPI spec
@app.get("/openapi-export", include_in_schema=False)
async def get_openapi_spec():
    """
    Returns the current OpenAPI spec generated by FastAPI.
    Used for downloading and converting to YAML.
    """
    return app.openapi()

# ✅ /spec/summary - for OpenAPI spec verification/debug
@app.get("/spec/summary", tags=["debug"], include_in_schema=False)
async def get_spec_summary():
    """
    Returns a summary of the OpenAPI spec for deployment verification.
    """
    spec = app.openapi()
    return {
        "title": spec.get("info", {}).get("title"),
        "version": spec.get("info", {}).get("version"),
        "number_of_paths": len(spec.get("paths", {})),
        "tags": [tag.get("name") for tag in spec.get("tags", []) if "name" in tag]
    }

# ✅ Save OpenAPI spec to file when app starts
def export_openapi_to_file():
    """
    Saves the OpenAPI spec to a file on startup.
    Creates the 'backend' folder if it doesn't exist.
    """
    output_dir = "backend"
    os.makedirs(output_dir, exist_ok=True)  # creates the folder if it doesn't exist
    output_path = os.path.join(output_dir, "project-echo-openapi.json")

    with open(output_path, "w") as f:
        json.dump(app.openapi(), f, indent=2)

    print(f"✅ OpenAPI spec exported to {output_path}")

export_openapi_to_file()
