import os
import json
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Import all routers
from app.routers import (
    audio_upload_router,
    species_predictor,
    auth_router,
    admin_budget,
    admin_services,
    insights,
    hmi,
    engine,
    sim,
    two_factor,
    public,
    iot,
    sensors,
    projects,
    detections,
)

# Initialize FastAPI app with metadata
app = FastAPI(
    title="Project Echo API",
    description="""
    Project Echo is an IoT-based system designed to record and analyze audio data for species identification and ecosystem monitoring.

    This API provides endpoints to:
    - Upload audio files
    - Simulate audio responses
    - Interface with HMI and audio engine modules
    """,
    version="1.0.0"
)

# Add CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allow all origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include all routers
app.include_router(hmi.router, tags=['hmi'], prefix='/hmi')
app.include_router(engine.router, tags=['engine'], prefix='/engine')
app.include_router(sim.router, tags=['sim'], prefix='/sim')
app.include_router(iot.router, tags=['iot'], prefix='/iot')
app.include_router(sensors.router, tags=['sensors'], prefix='/sensors')
app.include_router(public.router, tags=['public'], prefix='/public')

# API prefixed routers
app.include_router(audio_upload_router.router, tags=['audio'], prefix='/api')
app.include_router(admin_budget.router, tags=["admin"], prefix="/api")
app.include_router(admin_services.router, tags=["admin"], prefix="/api")
app.include_router(auth_router.router, tags=["auth"], prefix="/api")

# Unprefixed routers
app.include_router(projects.router)
app.include_router(two_factor.router)
app.include_router(species_predictor.router, tags=["predict"])
app.include_router(insights.router, tags=["insights"])
app.include_router(detections.router)

# --- Root Endpoint ---
@app.get("/", response_description="API Root")
def show_home():
    return 'Welcome to Project Echo API. Visit /docs for interactive documentation.'

# --- OpenAPI Spec Export Endpoints ---
@app.get("/openapi-export", include_in_schema=False)
async def get_openapi_spec():
    """
    Returns the current OpenAPI spec generated by FastAPI.
    Used for downloading and converting to YAML.
    """
    return app.openapi()

@app.get("/spec/summary", tags=["debug"], include_in_schema=False)
async def get_spec_summary():
    """
    Returns a summary of the OpenAPI spec for deployment verification.
    """
    spec = app.openapi()
    return {
        "title": spec.get("info", {}).get("title"),
        "version": spec.get("info", {}).get("version"),
        "number_of_paths": len(spec.get("paths", {})),
        "tags": [tag.get("name") for tag in spec.get("tags", []) if "name" in tag]
    }

def export_openapi_to_file():
    """
    Saves the OpenAPI spec to a file on startup.
    Creates the 'backend' folder if it doesn't exist.
    """
    output_dir = "backend"
    os.makedirs(output_dir, exist_ok=True)  # creates the folder if it doesn't exist
    output_path = os.path.join(output_dir, "project-echo-openapi.json")

    with open(output_path, "w") as f:
        json.dump(app.openapi(), f, indent=2)

    print(f"✅ OpenAPI spec exported to {output_path}")

export_openapi_to_file()
