apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out ./k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: echo-api
  name: echo_api
  namespace: default
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9080"
      port: 9080
      targetPort: 9080
  selector:
    io.kompose.service: echo-api
status:
  loadBalancer: {}
