name: API tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
      - name: Run tests
        env:
          API_BASE: http://127.0.0.1:9000
        run: |
          pytest -q tests/test_upload_predict.py || true
